{% set name = "fastf1" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastf1-{{ version }}.tar.gz
  sha256: adb506be8487801529a4cdb8a617dfc40ad5fe60f486cdbccdfe1b3c8c4a7ac2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests
    - requests-cache >=0.8.0
    - pandas >=1.1.0,<2.0.0
    - numpy >=1.17.3
    - scipy
    - thefuzz
    - matplotlib-base >=3.3.3
    - timple >=0.1.2
    - signalr-client-aio

test:
  imports:
    - fastf1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/theOehrly/Fast-F1
  summary: Wrapper library for F1 data and telemetry API with additional data processing capabilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
